version: "3.0"
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      NODE_ENV: dev
    volumes:
      - ./:/var/www/api-augustogehrke
  nginx:
    image: "nginx:1.18-alpine"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always
    depends_on:
      - node
